using System.Collections.Generic;

namespace CharSlotsTools
{
    public static class Data
    {

        public static Dictionary<CharacterName, string> charToSerial = new Dictionary<CharacterName, string>()
        {
            {CharacterName.BanjoKazooie,"SP1R4L"},
            {CharacterName.Bayonetta,"UMBR4"},
            {CharacterName.Bowser,"K1DN4P"},
            {CharacterName.BowserJr,"C10WN"},
            {CharacterName.Byleth,"S0TH15"},
            {CharacterName.CaptainFalcon,"SPE3D"},
            {CharacterName.Chrom,"F4TH3R"},
            {CharacterName.Cloud,"L1MIT"},
            {CharacterName.Corrin,"DR4G0N"},
            {CharacterName.Daisy,"S4RASA"},
            {CharacterName.DarkPit,"M1R40R"},
            {CharacterName.DarkSamus,"P4RAS1T3"},
            {CharacterName.DiddyKong,"K0N4"},
            {CharacterName.DonkeyKong,"B8NA54"},
            {CharacterName.DrMario,"P1L7"},
            {CharacterName.DuckHunt,"Z4PP3R"},
            {CharacterName.Falco,"4RW1NG"},
            {CharacterName.Fox,"SH1N3"},
            {CharacterName.Ganondorf,"P0W3R"},
            {CharacterName.Greninja,"N1NJ4"},
            {CharacterName.Hero,"5L1ME"},
            {CharacterName.IceClimbers,"N4N4P09O"},
            {CharacterName.Ike,"3THER"},
            {CharacterName.Incineroar,"L4R1A7"},
            {CharacterName.Inkling,"P41NT"},
            {CharacterName.Isabelle,"CR0S51NG"},
            {CharacterName.Jigglypuff,"51NG"},
            {CharacterName.Joker,"M45K"},
            {CharacterName.Kazuya,"CL1FF"},
            {CharacterName.Ken,"4M3R1CA"},
            {CharacterName.KingDedede,"8UNG3R"},
            {CharacterName.KingKRool,"4L1IGAT0R"},
            {CharacterName.Kirby,"5T4R"},
            {CharacterName.Link,"HYRU13"},
            {CharacterName.LittleMac,"L0U7S"},
            {CharacterName.Lucario,"4URA"},
            {CharacterName.Lucas,"BR0TH3R"},
            {CharacterName.Lucina,"F4T3"},
            {CharacterName.Luigi,"NUM3R2"},
            {CharacterName.Mario,"JUMPM4N"},
            {CharacterName.Marth,"H3R0K1N9"},
            {CharacterName.MegaMan,"R0CK"},
            {CharacterName.MetaKnight,"M85K"},
            {CharacterName.Mewtwo,"P5YCH16"},
            {CharacterName.MinMin,"4RMS"},
            {CharacterName.MrGameWatch,"FL4G"},
            {CharacterName.Ness,"PKF1R3"},
            {CharacterName.Olimar,"P1KMIN"},
            {CharacterName.PacMan,"GH05T"},
            {CharacterName.Palutena,"G0DD3S5"},
            {CharacterName.Peach,"R0Y4L"},
            {CharacterName.Pichu,"SH0CK"},
            {CharacterName.Pikachu,"M82C0T"},
            {CharacterName.PiranhaPlant,"FL0W3R"},
            {CharacterName.Pit,"H0L3"},
            {CharacterName.PokémonTrainer,"K3TCHUM"},
            {CharacterName.Pyra,"43G1S"},
            {CharacterName.Richter,"B3LM0NT"},
            {CharacterName.Ridley,"P1RAT3"},
            {CharacterName.ROB,"N1NT3ND0"},
            {CharacterName.Robin,"T80RON"},
            {CharacterName.Rosalina,"LUM8"},
            {CharacterName.Roy,"L10N"},
            {CharacterName.Ryu,"8AD0UK3N"},
            {CharacterName.Samus,"M0RP8"},
            {CharacterName.Sephiroth,"D35P41R"},
            {CharacterName.Sheik,"18AN5"},
            {CharacterName.Shulk,"FU7UR3"},
            {CharacterName.Simon,"DR4CULA"},
            {CharacterName.Snake,"M3TAL6E4R"},
            {CharacterName.Sonic,"F45T"},
            {CharacterName.Sora,"K1BL80E"},
            {CharacterName.Steve,"M1N3CRAFT"},
            {CharacterName.Terry,"G3Y5ER"},
            {CharacterName.ToonLink,"W1NDW4KER"},
            {CharacterName.Villager,"H0R1ZON5"},
            {CharacterName.Wario,"W4RI0"},
            {CharacterName.WiiFitTrainer,"B4LANC3"},
            {CharacterName.Wolf,"ST4RW01F"},
            {CharacterName.Yoshi,"D1N0"},
            {CharacterName.YoungLink,"T1ME"},
            {CharacterName.Zelda,"W1SD0M"},
            {CharacterName.ZeroSuitSamus,"SP85D3X"}
        };

        public static Dictionary<CharacterName, CharacterName[]> charToLikedCharacters = new Dictionary<CharacterName, CharacterName[]>()
        {
            {CharacterName.BanjoKazooie,new CharacterName[] {CharacterName.KingKRool,CharacterName.DonkeyKong,CharacterName.DiddyKong,CharacterName.BanjoKazooie,CharacterName.DuckHunt}},
            {CharacterName.Bayonetta,new CharacterName[] {CharacterName.Bowser,CharacterName.Pyra,CharacterName.Shulk,CharacterName.Sora}},
            {CharacterName.Bowser,new CharacterName[] {CharacterName.BowserJr,CharacterName.Peach,CharacterName.PiranhaPlant,CharacterName.DonkeyKong}},
            {CharacterName.BowserJr,new CharacterName[] {CharacterName.Bowser,CharacterName.Peach,CharacterName.PiranhaPlant,CharacterName.Inkling}},
            {CharacterName.Byleth,new CharacterName[] {CharacterName.Byleth,CharacterName.Samus,CharacterName.WiiFitTrainer,CharacterName.DarkPit,CharacterName.Richter}},
            {CharacterName.CaptainFalcon,new CharacterName[] {CharacterName.Fox,CharacterName.Falco,CharacterName.Lucario,CharacterName.Incineroar,CharacterName.Cloud}},
            {CharacterName.Chrom,new CharacterName[] {CharacterName.Robin,CharacterName.Lucina,CharacterName.Roy,CharacterName.Ike,CharacterName.BanjoKazooie}},
            {CharacterName.Cloud,new CharacterName[] {CharacterName.Ike,CharacterName.Ness,CharacterName.Daisy,CharacterName.ZeroSuitSamus,CharacterName.Ryu}},
            {CharacterName.Corrin,new CharacterName[] {CharacterName.Corrin,CharacterName.Bowser,CharacterName.Ridley,CharacterName.Kazuya,CharacterName.MiiFighter}},
            {CharacterName.Daisy,new CharacterName[] {CharacterName.Peach,CharacterName.Luigi,CharacterName.Olimar,CharacterName.Bowser,CharacterName.Villager}},
            {CharacterName.DarkPit,new CharacterName[] {CharacterName.MetaKnight,CharacterName.Kazuya,CharacterName.Wario}},
            {CharacterName.DarkSamus,new CharacterName[] {CharacterName.Ridley,CharacterName.Ganondorf,CharacterName.DarkPit}},
            {CharacterName.DiddyKong,new CharacterName[] {CharacterName.DonkeyKong,CharacterName.Jigglypuff,CharacterName.MiiFighter,CharacterName.Fox,CharacterName.Falco}},
            {CharacterName.DonkeyKong,new CharacterName[] {CharacterName.DiddyKong,CharacterName.Peach,CharacterName.MiiFighter}},
            {CharacterName.DrMario,new CharacterName[] {CharacterName.Luigi,CharacterName.Yoshi,CharacterName.Daisy}},
            {CharacterName.DuckHunt,new CharacterName[] {CharacterName.Isabelle,CharacterName.ROB,CharacterName.Lucas,CharacterName.Steve}},
            {CharacterName.Falco,new CharacterName[] {CharacterName.Fox,CharacterName.CaptainFalcon,CharacterName.Greninja}},
            {CharacterName.Fox,new CharacterName[] {CharacterName.Falco,CharacterName.Greninja,CharacterName.YoungLink,CharacterName.CaptainFalcon,CharacterName.Peach}},
            {CharacterName.Ganondorf,new CharacterName[] {CharacterName.MetaKnight,CharacterName.Kazuya,CharacterName.DarkSamus}},
            {CharacterName.Greninja,new CharacterName[] {CharacterName.Greninja,CharacterName.Incineroar,CharacterName.Sheik,CharacterName.Snake}},
            {CharacterName.Hero,new CharacterName[] {CharacterName.Hero,CharacterName.Link,CharacterName.DrMario}},
            {CharacterName.IceClimbers,new CharacterName[] {CharacterName.IceClimbers,CharacterName.Lucas,CharacterName.MrGameWatch}},
            {CharacterName.Ike,new CharacterName[] {CharacterName.Cloud,CharacterName.Joker,CharacterName.ZeroSuitSamus}},
            {CharacterName.Incineroar,new CharacterName[] {CharacterName.Ken,CharacterName.LittleMac,CharacterName.Cloud,CharacterName.Corrin}},
            {CharacterName.Inkling,new CharacterName[] {CharacterName.Kirby,CharacterName.BowserJr,CharacterName.Joker}},
            {CharacterName.Isabelle,new CharacterName[] {CharacterName.Villager,CharacterName.Jigglypuff,CharacterName.Peach,CharacterName.Daisy,CharacterName.IceClimbers}},
            {CharacterName.Jigglypuff,new CharacterName[] {CharacterName.Mewtwo,CharacterName.Pikachu,CharacterName.PokémonTrainer,CharacterName.Inkling,CharacterName.Isabelle}},
            {CharacterName.Joker,new CharacterName[] {CharacterName.Incineroar,CharacterName.Inkling,CharacterName.YoungLink}},
            {CharacterName.Kazuya,new CharacterName[] {CharacterName.MinMin,CharacterName.CaptainFalcon,CharacterName.Pit,CharacterName.Incineroar}},
            {CharacterName.Ken,new CharacterName[] {CharacterName.LittleMac,CharacterName.Ryu,CharacterName.Terry}},
            {CharacterName.KingDedede,new CharacterName[] {CharacterName.Bowser,CharacterName.PacMan,CharacterName.DonkeyKong}},
            {CharacterName.KingKRool,new CharacterName[] {CharacterName.KingDedede,CharacterName.Bowser,CharacterName.LittleMac}},
            {CharacterName.Kirby,new CharacterName[] {CharacterName.KingDedede,CharacterName.MetaKnight,CharacterName.Jigglypuff,CharacterName.Sora}},
            {CharacterName.Link,new CharacterName[] {CharacterName.YoungLink,CharacterName.ToonLink,CharacterName.Zelda,CharacterName.Hero,CharacterName.MrGameWatch}},
            {CharacterName.LittleMac,new CharacterName[] {CharacterName.Villager,CharacterName.Olimar,CharacterName.KingKRool}},
            {CharacterName.Lucario,new CharacterName[] {CharacterName.Snake,CharacterName.MetaKnight,CharacterName.IceClimbers,CharacterName.PokémonTrainer}},
            {CharacterName.Lucas,new CharacterName[] {CharacterName.Ness,CharacterName.Lucina,CharacterName.DuckHunt,CharacterName.Peach}},
            {CharacterName.Lucina,new CharacterName[] {CharacterName.Chrom,CharacterName.Marth,CharacterName.Shulk,CharacterName.MetaKnight}},
            {CharacterName.Luigi,new CharacterName[] {CharacterName.Mario,CharacterName.Daisy,CharacterName.Yoshi,CharacterName.Simon,CharacterName.Palutena}},
            {CharacterName.Mario,new CharacterName[] {CharacterName.Pyra,CharacterName.Luigi,CharacterName.Peach,CharacterName.Yoshi,CharacterName.Daisy}},
            {CharacterName.Marth,new CharacterName[] {CharacterName.Roy,CharacterName.Ike,CharacterName.Chrom,CharacterName.Richter}},
            {CharacterName.MegaMan,new CharacterName[] {CharacterName.Mario,CharacterName.Sonic,CharacterName.ROB}},
            {CharacterName.MetaKnight,new CharacterName[] {CharacterName.Lucina,CharacterName.MetaKnight,CharacterName.Sheik}},
            {CharacterName.Mewtwo,new CharacterName[] {CharacterName.Ganondorf,CharacterName.MetaKnight,CharacterName.KingDedede}},
            {CharacterName.MinMin,new CharacterName[] {CharacterName.CaptainFalcon,CharacterName.Peach,CharacterName.Wario}},
            {CharacterName.MrGameWatch,new CharacterName[] {CharacterName.PacMan,CharacterName.Mario,CharacterName.DonkeyKong,CharacterName.Link,CharacterName.Kirby}},
            {CharacterName.Ness,new CharacterName[] {CharacterName.Luigi,CharacterName.KingDedede,CharacterName.Pyra}},
            {CharacterName.Olimar,new CharacterName[] {CharacterName.Daisy,CharacterName.Villager,CharacterName.ToonLink,CharacterName.Pichu}},
            {CharacterName.PacMan,new CharacterName[] {CharacterName.MrGameWatch,CharacterName.ROB,CharacterName.Luigi,CharacterName.Kirby,CharacterName.BanjoKazooie}},
            {CharacterName.Palutena,new CharacterName[] {CharacterName.Pit,CharacterName.DarkPit,CharacterName.MegaMan}},
            {CharacterName.Peach,new CharacterName[] {CharacterName.Daisy,CharacterName.Mario,CharacterName.Lucas,CharacterName.Fox,CharacterName.Sheik}},
            {CharacterName.Pichu,new CharacterName[] {CharacterName.Pikachu,CharacterName.Ridley,CharacterName.Sephiroth}},
            {CharacterName.Pikachu,new CharacterName[] {CharacterName.Pichu,CharacterName.PokémonTrainer,CharacterName.ZeroSuitSamus}},
            {CharacterName.PiranhaPlant,new CharacterName[] {CharacterName.Bowser,CharacterName.BowserJr,CharacterName.Daisy,CharacterName.Villager,CharacterName.Peach}},
            {CharacterName.Pit,new CharacterName[] {CharacterName.Palutena,CharacterName.MegaMan,CharacterName.DarkPit}},
            {CharacterName.PokémonTrainer,new CharacterName[] {CharacterName.Mewtwo,CharacterName.Pikachu,CharacterName.Greninja,CharacterName.Pichu,CharacterName.Byleth}},
            {CharacterName.Pyra,new CharacterName[] {CharacterName.Shulk,CharacterName.Bowser,CharacterName.CaptainFalcon,CharacterName.Roy}},
            {CharacterName.Richter,new CharacterName[] {CharacterName.Simon,CharacterName.Palutena,CharacterName.Marth,CharacterName.Pit}},
            {CharacterName.Ridley,new CharacterName[] {CharacterName.DarkSamus,CharacterName.Mario,CharacterName.MegaMan,CharacterName.Rosalina}},
            {CharacterName.ROB,new CharacterName[] {CharacterName.MegaMan,CharacterName.DuckHunt,CharacterName.MrGameWatch}},
            {CharacterName.Robin,new CharacterName[] {CharacterName.Chrom,CharacterName.Lucina,CharacterName.Robin,CharacterName.MiiFighter,CharacterName.Samus}},
            {CharacterName.Rosalina,new CharacterName[] { CharacterName.Sora,CharacterName.Peach,CharacterName.Mario,CharacterName.Rosalina,CharacterName.Olimar}},
            {CharacterName.Roy,new CharacterName[] {CharacterName.Chrom,CharacterName.Ike,CharacterName.Pyra,CharacterName.Hero}},
            {CharacterName.Ryu,new CharacterName[] {CharacterName.Lucario,CharacterName.Ken,CharacterName.ROB,CharacterName.Cloud}},
            {CharacterName.Samus,new CharacterName[] {CharacterName.ZeroSuitSamus,CharacterName.Pikachu,CharacterName.Snake,CharacterName.Rosalina,CharacterName.Steve}},
            {CharacterName.Sephiroth,new CharacterName[] {CharacterName.Ganondorf,CharacterName.Mario,CharacterName.Byleth}},
            {CharacterName.Sheik,new CharacterName[] {CharacterName.Zelda,CharacterName.Link,CharacterName.YoungLink,CharacterName.Bayonetta,CharacterName.Cloud}},
            {CharacterName.Shulk,new CharacterName[] {CharacterName.Pyra,CharacterName.Lucario,CharacterName.ZeroSuitSamus,CharacterName.BanjoKazooie,CharacterName.Cloud}},
            {CharacterName.Simon,new CharacterName[] {CharacterName.Richter,CharacterName.Zelda,CharacterName.Palutena}},
            {CharacterName.Snake,new CharacterName[] {CharacterName.Lucario,CharacterName.MetaKnight,CharacterName.Bayonetta,CharacterName.Greninja}},
            {CharacterName.Sonic,new CharacterName[] {CharacterName.CaptainFalcon,CharacterName.LittleMac,CharacterName.Sheik,CharacterName.Kirby}},
            {CharacterName.Sora, new CharacterName[] {CharacterName.DuckHunt,CharacterName.Cloud,CharacterName.Mario,CharacterName.Isabelle}},
            {CharacterName.Steve,new CharacterName[] {CharacterName.MiiFighter,CharacterName.Wolf,CharacterName.PokémonTrainer,CharacterName.DuckHunt,CharacterName.Villager}},
            {CharacterName.Terry,new CharacterName[] {CharacterName.DrMario,CharacterName.Ken,CharacterName.Wolf,CharacterName.Pyra,CharacterName.MinMin}},
            {CharacterName.ToonLink,new CharacterName[] {CharacterName.Zelda,CharacterName.DiddyKong,CharacterName.Villager}},
            {CharacterName.Villager,new CharacterName[] {CharacterName.Isabelle,CharacterName.Pikachu,CharacterName.MiiFighter,CharacterName.Falco,CharacterName.Steve}},
            {CharacterName.Wario,new CharacterName[] {CharacterName.PiranhaPlant,CharacterName.Wario,CharacterName.KingKRool,CharacterName.YoungLink}},
            {CharacterName.WiiFitTrainer,new CharacterName[] {CharacterName.Sonic,CharacterName.Byleth,CharacterName.Falco,CharacterName.Pichu,CharacterName.Jigglypuff}},
            {CharacterName.Wolf,new CharacterName[] {CharacterName.Ridley,CharacterName.Snake,CharacterName.CaptainFalcon,CharacterName.Samus}},
            {CharacterName.Yoshi,new CharacterName[] {CharacterName.Mario,CharacterName.Luigi,CharacterName.Wario,CharacterName.Kirby,CharacterName.Yoshi}},
            {CharacterName.YoungLink,new CharacterName[] {CharacterName.Zelda,CharacterName.PokémonTrainer,CharacterName.Joker}},
            {CharacterName.Zelda,new CharacterName[] {CharacterName.Link,CharacterName.YoungLink,CharacterName.ToonLink,CharacterName.Simon,CharacterName.Byleth}},
            {CharacterName.ZeroSuitSamus,new CharacterName[] {CharacterName.Samus,CharacterName.Pikachu,CharacterName.Shulk,CharacterName.Sephiroth,CharacterName.Kirby}}
        };

        public static Dictionary<CharacterName, CharacterName[]> charToDislikedCharacters = new Dictionary<CharacterName, CharacterName[]>()
        {
            {CharacterName.BanjoKazooie, new CharacterName[] {CharacterName.Bayonetta,CharacterName.IceClimbers,CharacterName.Sonic,CharacterName.Chrom}},
            {CharacterName.Bayonetta, new CharacterName[] {CharacterName.Pit,CharacterName.Kirby,CharacterName.Palutena}},
            {CharacterName.Bowser, new CharacterName[] {CharacterName.Mario,CharacterName.Luigi,CharacterName.Daisy,CharacterName.Yoshi}},
            {CharacterName.BowserJr, new CharacterName[] {CharacterName.Mario,CharacterName.Luigi,CharacterName.Bayonetta}},
            {CharacterName.Byleth, new CharacterName[] {CharacterName.Ganondorf,CharacterName.BowserJr,CharacterName.PacMan,CharacterName.Simon}},
            {CharacterName.CaptainFalcon, new CharacterName[] {CharacterName.Kazuya,CharacterName.Ridley,CharacterName.DrMario,CharacterName.CaptainFalcon}},
            {CharacterName.Chrom, new CharacterName[] {CharacterName.Corrin,CharacterName.Ganondorf,CharacterName.Pichu}},
            {CharacterName.Cloud, new CharacterName[] {CharacterName.Sephiroth,CharacterName.Marth,CharacterName.PacMan}},
            {CharacterName.Corrin, new CharacterName[] {CharacterName.Ganondorf,CharacterName.Roy,CharacterName.Lucina}},
            {CharacterName.Daisy, new CharacterName[] {CharacterName.PiranhaPlant,CharacterName.PacMan,CharacterName.Hero}},
            {CharacterName.DarkPit, new CharacterName[] {CharacterName.Pit,CharacterName.Palutena,CharacterName.WiiFitTrainer}},
            {CharacterName.DarkSamus, new CharacterName[] {CharacterName.Samus,CharacterName.ZeroSuitSamus,CharacterName.Fox,CharacterName.Wolf}},
            {CharacterName.DiddyKong, new CharacterName[] {CharacterName.KingKRool,CharacterName.Bowser,CharacterName.DrMario}},
            {CharacterName.DonkeyKong, new CharacterName[] {CharacterName.KingKRool,CharacterName.LittleMac,CharacterName.Mario}},
            {CharacterName.DrMario, new CharacterName[] {CharacterName.KingKRool,CharacterName.Wario,CharacterName.Mario,CharacterName.KingDedede}},
            {CharacterName.DuckHunt, new CharacterName[] {CharacterName.BanjoKazooie,CharacterName.Daisy,CharacterName.Olimar}},
            {CharacterName.Falco, new CharacterName[] {CharacterName.Wolf,CharacterName.Terry,CharacterName.Corrin}},
            {CharacterName.Fox, new CharacterName[] {CharacterName.Wolf,CharacterName.Sheik,CharacterName.MetaKnight}},
            {CharacterName.Ganondorf, new CharacterName[] {CharacterName.Link,CharacterName.YoungLink,CharacterName.ToonLink,CharacterName.Sheik,CharacterName.Zelda}},
            {CharacterName.Greninja, new CharacterName[] {CharacterName.PokémonTrainer,CharacterName.PiranhaPlant,CharacterName.Shulk}},
            {CharacterName.Hero, new CharacterName[] {CharacterName.Ganondorf,CharacterName.Robin,CharacterName.Snake}},
            {CharacterName.IceClimbers, new CharacterName[] {CharacterName.Mario,CharacterName.Incineroar,CharacterName.Pyra}},
            {CharacterName.Ike, new CharacterName[] {CharacterName.Link,CharacterName.Rosalina,CharacterName.Richter}},
            {CharacterName.Incineroar, new CharacterName[] {CharacterName.BowserJr,CharacterName.Villager,CharacterName.KingKRool,CharacterName.Isabelle}},
            {CharacterName.Inkling, new CharacterName[] {CharacterName.Mario,CharacterName.Link,CharacterName.PokémonTrainer,CharacterName.Inkling}},
            {CharacterName.Isabelle, new CharacterName[] {CharacterName.Incineroar,CharacterName.Joker,CharacterName.Wario,CharacterName.Yoshi}},
            {CharacterName.Jigglypuff, new CharacterName[] {CharacterName.Robin,CharacterName.Ryu,CharacterName.Shulk}},
            {CharacterName.Joker, new CharacterName[] {CharacterName.KingKRool,CharacterName.Bowser,CharacterName.KingDedede,CharacterName.Ganondorf,CharacterName.Ridley}},
            {CharacterName.Kazuya, new CharacterName[] {CharacterName.Kazuya,CharacterName.Kirby,CharacterName.Palutena,CharacterName.Terry,CharacterName.Richter}},
            {CharacterName.Ken, new CharacterName[] {CharacterName.Incineroar,CharacterName.Kazuya,CharacterName.Ganondorf}},
            {CharacterName.KingDedede, new CharacterName[] {CharacterName.Kirby,CharacterName.MetaKnight,CharacterName.KingKRool}},
            {CharacterName.KingKRool, new CharacterName[] {CharacterName.DonkeyKong,CharacterName.DiddyKong,CharacterName.BanjoKazooie}},
            {CharacterName.Kirby, new CharacterName[] {CharacterName.KingKRool,CharacterName.Yoshi,CharacterName.WiiFitTrainer}},
            {CharacterName.Link, new CharacterName[] {CharacterName.Ganondorf,CharacterName.Marth,CharacterName.MetaKnight}},
            {CharacterName.LittleMac, new CharacterName[] {CharacterName.Ken,CharacterName.Incineroar,CharacterName.Samus,CharacterName.MinMin,CharacterName.DonkeyKong}},
            {CharacterName.Lucario, new CharacterName[] {CharacterName.Lucario,CharacterName.Mewtwo,CharacterName.Ken,CharacterName.Ryu}},
            {CharacterName.Lucas, new CharacterName[] {CharacterName.Lucas,CharacterName.IceClimbers,CharacterName.Bayonetta}},
            {CharacterName.Lucina, new CharacterName[] {CharacterName.Robin,CharacterName.Sephiroth,CharacterName.Lucas}},
            {CharacterName.Luigi, new CharacterName[] {CharacterName.Bowser,CharacterName.BowserJr,CharacterName.Ridley}},
            {CharacterName.Mario, new CharacterName[] {CharacterName.Ridley,CharacterName.Wario,CharacterName.Bowser,CharacterName.BowserJr,CharacterName.PiranhaPlant}},
            {CharacterName.Marth, new CharacterName[] {CharacterName.Lucina,CharacterName.ToonLink,CharacterName.Ryu}},
            {CharacterName.MegaMan, new CharacterName[] {CharacterName.Ridley,CharacterName.DrMario,CharacterName.PacMan,CharacterName.DarkSamus,CharacterName.IceClimbers}},
            {CharacterName.MetaKnight, new CharacterName[] {CharacterName.Kirby,CharacterName.KingDedede,CharacterName.ToonLink}},
            {CharacterName.Mewtwo, new CharacterName[] {CharacterName.PokémonTrainer,CharacterName.Ryu,CharacterName.Lucario}},
            {CharacterName.MinMin, new CharacterName[] {CharacterName.Kirby,CharacterName.KingDedede,CharacterName.Kazuya}},
            {CharacterName.MrGameWatch, new CharacterName[] {CharacterName.Pyra,CharacterName.Roy,CharacterName.Incineroar}},
            {CharacterName.Ness, new CharacterName[] {CharacterName.Mewtwo,CharacterName.Lucario,CharacterName.Wario,CharacterName.Bayonetta}},
            {CharacterName.Olimar, new CharacterName[] {CharacterName.BowserJr,CharacterName.Terry,CharacterName.DiddyKong}},
            {CharacterName.PacMan, new CharacterName[] {CharacterName.MinMin,CharacterName.Steve,CharacterName.Cloud,CharacterName.Sora}},
            {CharacterName.Palutena, new CharacterName[] {CharacterName.Bayonetta,CharacterName.Greninja,CharacterName.Incineroar,CharacterName.Ganondorf,CharacterName.Snake}},
            {CharacterName.Peach, new CharacterName[] {CharacterName.Bowser,CharacterName.MinMin,CharacterName.Simon}},
            {CharacterName.Pichu, new CharacterName[] {CharacterName.PokémonTrainer,CharacterName.Steve,CharacterName.Greninja}},
            {CharacterName.Pikachu, new CharacterName[] {CharacterName.Mewtwo,CharacterName.Greninja,CharacterName.ROB}},
            {CharacterName.PiranhaPlant, new CharacterName[] {CharacterName.Mario,CharacterName.Luigi,CharacterName.Terry,CharacterName.Joker}},
            {CharacterName.Pit, new CharacterName[] {CharacterName.Bayonetta,CharacterName.Kazuya,CharacterName.Kirby}},
            {CharacterName.PokémonTrainer, new CharacterName[] {CharacterName.PokémonTrainer,CharacterName.WiiFitTrainer,CharacterName.Jigglypuff}},
            {CharacterName.Pyra, new CharacterName[] {CharacterName.Greninja,CharacterName.Mario,CharacterName.ZeroSuitSamus,CharacterName.Link}},
            {CharacterName.Richter, new CharacterName[] {CharacterName.Kazuya,CharacterName.Sephiroth,CharacterName.Inkling}},
            {CharacterName.Ridley, new CharacterName[] {CharacterName.Samus,CharacterName.ZeroSuitSamus,CharacterName.MiiFighter}},
            {CharacterName.ROB, new CharacterName[] {CharacterName.Ganondorf,CharacterName.Ridley,CharacterName.Villager}},
            {CharacterName.Robin, new CharacterName[] {CharacterName.Ridley,CharacterName.Marth,CharacterName.DuckHunt,CharacterName.Falco,CharacterName.CaptainFalcon}},
            {CharacterName.Rosalina, new CharacterName[] {CharacterName.Bowser,CharacterName.Wolf,CharacterName.Ridley}},
            {CharacterName.Roy, new CharacterName[] {CharacterName.Corrin,CharacterName.DarkSamus,CharacterName.Inkling}},
            {CharacterName.Ryu, new CharacterName[] {CharacterName.Ganondorf,CharacterName.Terry,CharacterName.Ness,CharacterName.Jigglypuff}},
            {CharacterName.Samus, new CharacterName[] {CharacterName.Ridley,CharacterName.DarkSamus,CharacterName.ROB}},
            {CharacterName.Sephiroth, new CharacterName[] {CharacterName.Cloud,CharacterName.Zelda,CharacterName.Hero,CharacterName.Sora}},
            {CharacterName.Sheik, new CharacterName[] {CharacterName.Ganondorf,CharacterName.Isabelle,CharacterName.Ike}},
            {CharacterName.Shulk, new CharacterName[] {CharacterName.MegaMan,CharacterName.Mewtwo,CharacterName.DarkPit}},
            {CharacterName.Simon, new CharacterName[] {CharacterName.Kazuya,CharacterName.MetaKnight,CharacterName.DarkPit}},
            {CharacterName.Snake, new CharacterName[] {CharacterName.Wario,CharacterName.Ken,CharacterName.Sonic}},
            {CharacterName.Sonic, new CharacterName[] {CharacterName.Mario,CharacterName.Robin,CharacterName.Incineroar,CharacterName.Jigglypuff}},
            {CharacterName.Sora, new CharacterName[] {CharacterName.Sephiroth,CharacterName.Kirby,CharacterName.Sonic}},
            {CharacterName.Steve, new CharacterName[] {CharacterName.Ridley,CharacterName.Steve,CharacterName.MrGameWatch}},
            {CharacterName.Terry, new CharacterName[] {CharacterName.Villager,CharacterName.Sonic,CharacterName.Ryu,CharacterName.DuckHunt}},
            {CharacterName.ToonLink, new CharacterName[] {CharacterName.Ganondorf,CharacterName.Sephiroth,CharacterName.MegaMan}},
            {CharacterName.Villager, new CharacterName[] {CharacterName.Samus,CharacterName.Ridley,CharacterName.Fox}},
            {CharacterName.Wario, new CharacterName[] {CharacterName.Mario,CharacterName.DonkeyKong,CharacterName.WiiFitTrainer,CharacterName.Ness}},
            {CharacterName.WiiFitTrainer, new CharacterName[] {CharacterName.Wario,CharacterName.KingDedede,CharacterName.Rosalina}},
            {CharacterName.Wolf, new CharacterName[] {CharacterName.Fox,CharacterName.Falco,CharacterName.YoungLink}},
            {CharacterName.Yoshi, new CharacterName[] {CharacterName.Bowser,CharacterName.BowserJr,CharacterName.Daisy}},
            {CharacterName.YoungLink, new CharacterName[] {CharacterName.Ganondorf,CharacterName.Sephiroth,CharacterName.Ness}},
            {CharacterName.Zelda, new CharacterName[] {CharacterName.Ganondorf,CharacterName.Olimar,CharacterName.Wolf}},
            {CharacterName.ZeroSuitSamus, new CharacterName[] {CharacterName.Ridley,CharacterName.DarkSamus,CharacterName.Corrin}}
        };

        public static Dictionary<CharacterName, string[]> charToLikedModules = new Dictionary<CharacterName, string[]>()
        {
            {CharacterName.BanjoKazooie,new string[] { "spellingBee", "yellowHexabuttons"}},
            {CharacterName.Bayonetta,new string[] { "TheClockModule", "arsGoetiaIdentification"}},
            {CharacterName.Bowser,new string[] { "PartyTime", "superparsing"}},
            {CharacterName.BowserJr,new string[] { "graffitiNumbers", "Painting"}},
            {CharacterName.Byleth,new string[] { "HogwartsModule", "curriculum"}},
            {CharacterName.CaptainFalcon,new string[] { "DUCKDUCKGOOSE", "kataBurnout"}},
            {CharacterName.Chrom,new string[] { "TheArena", "symbolicTasha"}},
            {CharacterName.Cloud,new string[] { "KanjiModule", "PianoKeys"}},
            {CharacterName.Corrin,new string[] { "matchmaker", "dragonEnergy"}},
            {CharacterName.Daisy,new string[] { "flowerPatch", "TennisModule"}},
            {CharacterName.DarkPit,new string[] { "blackCipher", "blackArrowsModule"}},
            {CharacterName.DarkSamus,new string[] { "Phosphorescence", "exoplanets"}},
            {CharacterName.DiddyKong,new string[] { "iconic", "TheBulbModule"}},
            {CharacterName.DonkeyKong,new string[] { "ladders", "boxing"}},
            {CharacterName.DrMario,new string[] { "DrDoctorModule", "MusicRhythms"}},
            {CharacterName.DuckHunt,new string[] { "hunting", "theDuck"}},
            {CharacterName.Falco,new string[] { "lasers", "lightspeed"}},
            {CharacterName.Fox,new string[] { "matchRefereeing", "WildSide"}},
            {CharacterName.Ganondorf,new string[] { "necronomicon", "BlackHoleModule"}},
            {CharacterName.Greninja,new string[] { "rainModule", "moon"}},
            {CharacterName.Hero,new string[] { "spwizAdventureGame", "console"}},
            {CharacterName.IceClimbers,new string[] { "iceCreamModule", "snowflakes"}},
            {CharacterName.Ike,new string[] { "daylightDirections", "FriendshipModule"}},
            {CharacterName.Incineroar,new string[] { "streetFighter", "GSPathfinder"}},
            {CharacterName.Inkling,new string[] { "Painting", "spillingPaint"}},
            {CharacterName.Isabelle,new string[] { "OneHundredAndOneDalmatiansModule", "taxReturns"}},
            {CharacterName.Jigglypuff,new string[] { "ksmDreamcipher", "shaker"}},
            {CharacterName.Joker,new string[] { "KritHoldUps", "thedealmaker"}},
            {CharacterName.Kazuya,new string[] { "GSPathfinder", "boxing"}},
            {CharacterName.Ken,new string[] { "streetFighter", "spangledStars"}},
            {CharacterName.KingDedede,new string[] { "fruits", "remotemath"}},
            {CharacterName.KingKRool,new string[] { "treasureHunt", "boxing"}},
            {CharacterName.Kirby,new string[] { "ingredients", "starmap_reconstruction"}},
            {CharacterName.Link,new string[] { "dungeon", "metamem"}},
            {CharacterName.LittleMac,new string[] { "boxing", "smallCircle"}},
            {CharacterName.Lucario,new string[] { "UnownCipher", "theCruelDuck"}},
            {CharacterName.Lucas,new string[] { "EarthboundModule", "hearthur"}},
            {CharacterName.Lucina,new string[] { "PurgatoryModule", "nomai"}},
            {CharacterName.Luigi,new string[] { "MazeV2", "GSCorridors"}},
            {CharacterName.Mario,new string[] { "Questionmark", "PartyTime"}},
            {CharacterName.Marth,new string[] { "fencing", "heraldry"}},
            {CharacterName.MegaMan,new string[] { "megaMan2", "lightspeed"}},
            {CharacterName.MetaKnight,new string[] { "fencing", "mysterymodule"}},
            {CharacterName.Mewtwo,new string[] { "UnownCipher", "characterSlots"}},
            {CharacterName.MinMin,new string[] { "wireSpaghetti", "chineseCounting"}},
            {CharacterName.MrGameWatch,new string[] { "ksmHighScore", "pixelcipher"}},
            {CharacterName.Ness,new string[] { "EarthboundModule", "pigpenCycle"}},
            {CharacterName.Olimar,new string[] { "flowerPatch", "fruits"}},
            {CharacterName.PacMan,new string[] { "Maze", "ghostMovement"}},
            {CharacterName.Palutena,new string[] { "notreDameCipher", "CreationModule"}},
            {CharacterName.Peach,new string[] { "TwoPersuasiveButtons", "pinkArrows"}},
            {CharacterName.Pichu,new string[] { "Probing", "monsplodeFight"}},
            {CharacterName.Pikachu,new string[] { "charge", "monsplodeWho"}},
            {CharacterName.PiranhaPlant,new string[] { "PlantIdentification", "flowerPatch"}},
            {CharacterName.Pit,new string[] { "WhiteArrows", "PurgatoryModule"}},
            {CharacterName.PokémonTrainer,new string[] { "TheArena", "kataDeckCreating"}},
            {CharacterName.Pyra,new string[] { "burnt", "lightspeed"}},
            {CharacterName.Richter,new string[] { "HitmanModule", "VoronoiMazeModule"}},
            {CharacterName.Ridley,new string[] { "murder", "space_traders"}},
            {CharacterName.ROB,new string[] { "robotProgramming", "turtleRobot"}},
            {CharacterName.Robin,new string[] { "necronomicon", "matchmaker"}},
            {CharacterName.Rosalina,new string[] { "exoplanets", "constellations"}},
            {CharacterName.Roy,new string[] { "redCipher", "notreDameCipher"}},
            {CharacterName.Ryu,new string[] { "PianoKeys", "KanjiModule"}},
            {CharacterName.Samus,new string[] { "xelDcrypt", "hexOrbits"}},
            {CharacterName.Sephiroth,new string[] { "greatVoid", "burnt"}},
            {CharacterName.Sheik,new string[] { "GSCorridors", "inselectables"}},
            {CharacterName.Shulk,new string[] { "Wendithapn", "FriendshipModule"}},
            {CharacterName.Simon,new string[] { "SimonSpinsModule", "simonSimons"}},
            {CharacterName.Snake,new string[] { "siloAuthorization", "snakesAndLadders"}},
            {CharacterName.Sonic,new string[] { "sonic", "sonicKnuckles"}},
            {CharacterName.Sora, new string[] { "OneHundredAndOneDalmatiansModule", "LionsShareModule"} },
            {CharacterName.Steve,new string[] { "minecraftCipher", "Netherite"}},
            {CharacterName.Terry,new string[] { "blockbusters", "CrackboxModule"}},
            {CharacterName.ToonLink,new string[] { "RailwayCargoLoading", "toonEnough"}},
            {CharacterName.Villager,new string[] { "retirement", "xelButterflies"}},
            {CharacterName.Wario,new string[] { "numberNimbleness", "TheKanyeEncounter"}},
            {CharacterName.WiiFitTrainer,new string[] { "MotionSense", "mashematics"}},
            {CharacterName.Wolf,new string[] { "wolfGoatCabbageModule", "pigpenRotations"}},
            {CharacterName.Yoshi,new string[] { "fruits", "bigegg"}},
            {CharacterName.YoungLink,new string[] { "melodicMessage", "PianoKeys"}},
            {CharacterName.Zelda,new string[] { "dungeon", "warningSigns"}},
            {CharacterName.ZeroSuitSamus,new string[] { "XRayModule", "lgndLombaxCubes"}}
        };

        public static Dictionary<CharacterName, string[]> charToDislikedModules = new Dictionary<CharacterName, string[]>()
        {
            {CharacterName.BanjoKazooie,new string[] { "HogwartsModule", "cheepCheckout"}},
            {CharacterName.Bayonetta,new string[] { "PurgatoryModule", "gatekeeper"}},
            {CharacterName.Bowser,new string[] { "AquariumModule", "VarietyModule"}},
            {CharacterName.BowserJr,new string[] { "Censorship", "rainModule"}},
            {CharacterName.Byleth,new string[] { "SymbolCycleModule", "greatVoid"}},
            {CharacterName.CaptainFalcon,new string[] { "maintenance", "RailwayCargoLoading"}},
            {CharacterName.Chrom,new string[] { "sevenDeadlySins", "simonStumbles"}},
            {CharacterName.Cloud,new string[] { "burnt", "Skewers"}},
            {CharacterName.Corrin,new string[] { "BattleshipModule", "simonStumbles"}},
            {CharacterName.Daisy,new string[] { "langtonAnt", "neutralization"}},
            {CharacterName.DarkPit,new string[] { "Mastermind Simple", "melodicMessage"}},
            {CharacterName.DarkSamus,new string[] { "antichamber", "periodicTable"}},
            {CharacterName.DiddyKong,new string[] { "WalkingCubeModule", "partialDerivatives"}},
            {CharacterName.DonkeyKong,new string[] { "equationsXModule", "hereditaryBaseNotationModule"}},
            {CharacterName.DrMario,new string[] { "tetrisSprint", "boneAppleTea"}},
            {CharacterName.DuckHunt,new string[] { "groceryStore", "AppreciateArt"}},
            {CharacterName.Falco,new string[] { "duckKonundrum", "DUCKDUCKGOOSE"}},
            {CharacterName.Fox,new string[] { "polygons", "powModule"}},
            {CharacterName.Ganondorf,new string[] { "TennisModule", "mSeq"}},
            {CharacterName.Greninja,new string[] { "desertBus", "boxing"}},
            {CharacterName.Hero,new string[] { "colorOneTwo", "HigherOrLower"}},
            {CharacterName.IceClimbers,new string[] { "bigegg", "seaBearAttacksModule"}},
            {CharacterName.Ike,new string[] { "IKEADocuments", "qSwedishMaze"}},
            {CharacterName.Incineroar,new string[] { "boxing", "explodingMittens"}},
            {CharacterName.Inkling,new string[] { "graffitiNumbers", "rainHellModule"}},
            {CharacterName.Isabelle,new string[] { "retirement", "breaktime"}},
            {CharacterName.Jigglypuff,new string[] { "TheExplodingPen", "simonSupports"}},
            {CharacterName.Joker,new string[] { "giantsDrink", "BoardWalk"}},
            {CharacterName.Kazuya,new string[] { "binaryTree", "hereditaryBaseNotationModule"}},
            {CharacterName.Ken,new string[] { "OrientationCube", "KanjiModule"}},
            {CharacterName.KingDedede,new string[] { "theCruelDuck", "Mastermind Cruel"}},
            {CharacterName.KingKRool,new string[] { "identityParade", "GameOfLifeSimple"}},
            {CharacterName.Kirby,new string[] { "StareModule", "cube"}},
            {CharacterName.Link,new string[] { "dungeon2", "hyperlink"}},
            {CharacterName.LittleMac,new string[] { "NeedyAirTrafficController", "BigCircle"}},
            {CharacterName.Lucario,new string[] { "TheHeart", "characterSlots"}},
            {CharacterName.Lucas,new string[] { "riskyWires", "SimonShoutsModule"}},
            {CharacterName.Lucina,new string[] { "necronomicon", "InfiniteLoop"}},
            {CharacterName.Luigi,new string[] { "ghostMovement", "qkUCN"}},
            {CharacterName.Mario,new string[] { "AppreciateArt", "sonic"}},
            {CharacterName.Marth,new string[] { "MafiaModule", "calendar"}},
            {CharacterName.MegaMan,new string[] { "DrDoctorModule", "CaptchaModule"}},
            {CharacterName.MetaKnight,new string[] { "identityParade", "xelFaceRecognition"}},
            {CharacterName.Mewtwo,new string[] { "ZooModule", "monsplodeFight"}},
            {CharacterName.MinMin,new string[] { "ChickenNuggets", "tacoTuesday"}},
            {CharacterName.MrGameWatch,new string[] { "spwiz3DMaze", "maze3"}},
            {CharacterName.Ness,new string[] { "SimonSpeaksModule", "krazzBlaseball"}},
            {CharacterName.Olimar,new string[] { "marqueeMorseModule", "cruelStars"}},
            {CharacterName.PacMan,new string[] { "salts", "frankensteinsIndicator"}},
            {CharacterName.Palutena,new string[] { "Netherite", "PurgatoryModule"}},
            {CharacterName.Peach,new string[] { "Painting", "perceptron"}},
            {CharacterName.Pichu,new string[] { "resistors", "smallCircle"}},
            {CharacterName.Pikachu,new string[] { "resistors", "hideAndSeek"}},
            {CharacterName.PiranhaPlant,new string[] { "neutralization", "desertBus"}},
            {CharacterName.Pit,new string[] { "mcdNatures", "necronomicon"}},
            {CharacterName.PokémonTrainer,new string[] { "greekCalculus", "CrazyTalk"}},
            {CharacterName.Pyra,new string[] { "cooking", "lasers"}},
            {CharacterName.Richter,new string[] { "sevenDeadlySins", "lgndEightPages"}},
            {CharacterName.Ridley,new string[] { "lightspeed", "macroMemory"}},
            {CharacterName.ROB,new string[] { "CaptchaModule", "PointlessMachines"}},
            {CharacterName.Robin,new string[] { "skyrim", "Amnesia"}},
            {CharacterName.Rosalina,new string[] { "lyingIndicators", "prankster"}},
            {CharacterName.Roy,new string[] { "dragonEnergy", "safetySquare"}},
            {CharacterName.Ryu,new string[] { "EnglishTest", "CrazyTalk"}},
            {CharacterName.Samus,new string[] { "hereditaryBaseNotationModule", "hexNull"}},
            {CharacterName.Sephiroth,new string[] { "PartyTime", "xelSymmetriesOfASquare"}},
            {CharacterName.Sheik,new string[] { "TennisModule", "Filibuster"}},
            {CharacterName.Shulk,new string[] { "nomai", "TribalCouncil"}},
            {CharacterName.Simon,new string[] { "nonverbalSimon", "tashaSqueals"}},
            {CharacterName.Snake,new string[] { "stateOfAggregation", "Telepathy"}},
            {CharacterName.Sonic,new string[] { "devilishEggs", "robotProgramming"}},
            {CharacterName.Sora, new string[] {"matrix", "KritLockpickMaze"}},
            {CharacterName.Steve,new string[] { "greatVoid", "sphere"}},
            {CharacterName.Terry,new string[] { "streetFighter", "mortalKombat"}},
            {CharacterName.ToonLink,new string[] { "dungeon2", "TheHypercubeModule"}},
            {CharacterName.Villager,new string[] { "3dTunnels", "taxReturns"}},
            {CharacterName.Wario,new string[] { "SplittingTheLootModule", "burglarAlarm"}},
            {CharacterName.WiiFitTrainer,new string[] { "ChickenNuggets", "papasPizzeria"}},
            {CharacterName.Wolf,new string[] { "witheredFoxy", "DUCKDUCKGOOSE"}},
            {CharacterName.Yoshi,new string[] { "devilishEggs", "flowerPatch"}},
            {CharacterName.YoungLink,new string[] { "dungeon2", "CruelPianoKeys"}},
            {CharacterName.Zelda,new string[] { "ForgetMeNow", "theBlock"}},
            {CharacterName.ZeroSuitSamus,new string[] { "GSXenocryst", "VoronoiMazeModule"}}
        };
        /// <summary>
        /// Edgework codes :
        ///     sn : serial number
        ///         present/sum/end/dr
        ///             character
        ///         motif
        ///             X/#
        ///         count
        ///             X/#
        ///                 more/less/exact
        ///     needy : needy present
        ///     stage : stage number (1,2,3)
        ///     slot : slot placement (L,M,R)
        ///     ind : indicator
        ///         identify : exact indicator
        ///             bulb : lit/unlit/any
        ///                 name
        ///         compare : lit vs unlit
        ///             lit/unlit/exact
        ///         bulb : unlit/lit/any
        ///             more/less/exact
        ///     str : strikes
        ///         exact/more/less
        ///             number
        ///         1left
        ///     modules :
        ///         total/solved
        ///             n/percent
        ///                 more/less/exact
        ///             divisible
        ///         compare : solved vs unsolved
        ///             solved/unsolved/exact
        ///     batteries
        ///         D/AA/all
        ///             more/less/exact
        ///         compare
        ///             D/AA/exact
        ///     kept
        ///     holders
        ///         more/less/exact
        ///     ports
        ///         empty/type/any
        ///             more/less
        ///         duplicates
        ///         onone
        ///     friend
        ///     time
        ///         left
        ///             more/less/exact
        ///                 value in seconds
        ///         used
        ///             more/less            
        ///     voltage
        ///         more/less
        ///     2factor
        ///     first
        ///     compare
        ///     widgetVanilla
        ///         more/less/exact
        ///     absentMore
        ///     widgetSum
        ///         stuff|other
        ///             more/less/exact
        ///     not (!)
        /// </summary>
        public static Dictionary<CharacterName, string> charToLikedEdgework = new Dictionary<CharacterName, string>()
        {
            {CharacterName.BanjoKazooie,"sn present 6"},
            {CharacterName.Bayonetta,"sn sum prime"},
            {CharacterName.Bowser,"stage 3"},
            {CharacterName.BowserJr,"needy"},
            {CharacterName.Byleth,"sn present 3"},
            {CharacterName.CaptainFalcon,"compare batteries ports"},
            {CharacterName.Chrom,"ind identify unlit FRQ"},
            {CharacterName.Cloud,"ind identify any SND"},
            {CharacterName.Corrin,"stage 3"},
            {CharacterName.Daisy,"needy"},
            {CharacterName.DarkPit,"ind compare unlit"},
            {CharacterName.DarkSamus,"ind compare exact"},
            {CharacterName.DiddyKong,"ports Serial more 0"},
            {CharacterName.DonkeyKong,"ports Parallel more 0"},
            {CharacterName.DrMario,"ports Serial more 1"},
            {CharacterName.DuckHunt,"str less 3"},
            {CharacterName.Falco,"batteries AA more 2"},
            {CharacterName.Fox,"batteries compare AA"},
            {CharacterName.Ganondorf,"modules solved divisible 3"},
            {CharacterName.Greninja,"ports empty more 0"},
            {CharacterName.Hero,"sn present 4"},
            {CharacterName.IceClimbers,"ports StereoRCA more 0"},
            {CharacterName.Ike,"ind compare exact"},
            {CharacterName.Incineroar,"ind lit more 0"},
            {CharacterName.Inkling,"holders exact 0"},
            {CharacterName.Isabelle,"modules compare unsolved"},
            {CharacterName.Jigglypuff,"ports PS2 more 0"},
            {CharacterName.Joker,"sn last 4"},
            {CharacterName.Kazuya,"batteries all exact 1"},
            {CharacterName.Ken,"ports DVI more 0"},
            {CharacterName.KingDedede,"batteries D more 0"},
            {CharacterName.KingKRool,"batteries all more 2"},
            {CharacterName.Kirby,"ports PS2|StereoRCA|CompositeVideo|ComponentVideo more 0"},
            {CharacterName.Link,"ind any more 2"},
            {CharacterName.LittleMac,"slot R"},
            {CharacterName.Lucario,"ports PS2 more 0"},
            {CharacterName.Lucas,"sn present 4"},
            {CharacterName.Lucina,"ind identify lit FRK"},
            {CharacterName.Luigi,"sn present L"},
            {CharacterName.Mario,"stage 1"},
            {CharacterName.Marth,"ind identify any BOB"},
            {CharacterName.MegaMan,"str exact 0"},
            {CharacterName.MetaKnight,"ind compare unlit"},
            {CharacterName.Mewtwo,"ports duplicates"},
            {CharacterName.MinMin,"sn count X exact 4"},
            {CharacterName.MrGameWatch,"ports RJ45 more 0"},
            {CharacterName.Ness,"slot M"},
            {CharacterName.Olimar,"sn dr 5"},
            {CharacterName.PacMan,"ind lit more 0"},
            {CharacterName.Palutena,"ind identify any CLR"},
            {CharacterName.Peach,"ind identify unlit TRN"},
            {CharacterName.Pichu,"str more 0"},
            {CharacterName.Pikachu,"voltage more 5"},
            {CharacterName.PiranhaPlant,"ind identify lit NSA"},
            {CharacterName.Pit,"ind compare lit"},
            {CharacterName.PokémonTrainer,"sn last even"},
            {CharacterName.Pyra,"sn last prime"},
            {CharacterName.Richter,"widgetSum ports|batteries exact 0"},
            {CharacterName.Ridley,"ind identify any FRQ"},
            {CharacterName.ROB,"ports AC more 0"},
            {CharacterName.Robin,"holders more 0"},
            {CharacterName.Rosalina,"ind any more 2"},
            {CharacterName.Roy,"ind identify lit SND"},
            {CharacterName.Ryu,"ind any exact 0"},
            {CharacterName.Samus,"ind compare lit"},
            {CharacterName.Sephiroth,"ind lit exact 0"},
            {CharacterName.Sheik,"first"},
            {CharacterName.Shulk,"time left exact 330"},
            {CharacterName.Simon,"slot L"},
            {CharacterName.Snake,"ind lit exact 0"},
            {CharacterName.Sonic,"time used less 10"},
            {CharacterName.Sora,"ind identify lit CAR" },
            {CharacterName.Steve,"ind identify lit BOB"},
            {CharacterName.Terry,"str 1left"},
            {CharacterName.ToonLink,"ind identify lit TRN"},
            {CharacterName.Villager,"modules solved percent more 50"},
            {CharacterName.Wario,"ind identify unlit CAR"},
            {CharacterName.WiiFitTrainer,"holders more 2"},
            {CharacterName.Wolf,"ind identify unlit SIG"},
            {CharacterName.Yoshi,"friend Yoshi"},
            {CharacterName.YoungLink,"time left more 3600"},
            {CharacterName.Zelda,"stage 3"},
            {CharacterName.ZeroSuitSamus,"str more 0"}
        };

        public static Dictionary<CharacterName, string> charToDislikedEdgework = new Dictionary<CharacterName, string>()
        {
            {CharacterName.BanjoKazooie,"sn last prime"},
            {CharacterName.Bayonetta,"str more 1"},
            {CharacterName.Bowser,"modules total n less 8"},
            {CharacterName.BowserJr,"slot L"},
            {CharacterName.Byleth,"str more 0"},
            {CharacterName.CaptainFalcon,"time left more 180"},
            {CharacterName.Chrom,"str exact 1"},
            {CharacterName.Cloud,"slot M"},
            {CharacterName.Corrin,"ind compare exact"},
            {CharacterName.Daisy,"time used more 50"},
            {CharacterName.DarkPit,"ind lit more 0"},
            {CharacterName.DarkSamus,"ports any less 1"},
            {CharacterName.DiddyKong,"batteries D exact 0"},
            {CharacterName.DonkeyKong,"batteries AA exact 0"},
            {CharacterName.DrMario,"voltage less 5.5"},
            {CharacterName.DuckHunt,"modules solved percent less 60"},
            {CharacterName.Falco,"batteries compare AA"},
            {CharacterName.Fox,"ports empty more 0"},
            {CharacterName.Ganondorf,"stage 3 not"},
            {CharacterName.Greninja,"2factor"},
            {CharacterName.Hero,"modules total divisible 4 not"},
            {CharacterName.IceClimbers,"ports PS2 more 0"},
            {CharacterName.Ike,"str more 0"},
            {CharacterName.Incineroar,"widgetVanilla less 5"},
            {CharacterName.Inkling,"stage 1 not"},
            {CharacterName.Isabelle,"time left more 600"},
            {CharacterName.Jigglypuff,"slot M not"},
            {CharacterName.Joker,"ind compare lit"},
            {CharacterName.Kazuya,"ports StereoRCA more 0"},
            {CharacterName.Ken,"sn motif XX not"},
            {CharacterName.KingDedede,"stage 3"},
            {CharacterName.KingKRool,"ports Serial|Parallel more 0"},
            {CharacterName.Kirby,"ports PS2 exact 0"},
            {CharacterName.Link,"batteries all less 3"},
            {CharacterName.LittleMac,"ports Parallel more 0"},
            {CharacterName.Lucario,"ind any exact 0"},
            {CharacterName.Lucas,"slot L not"},
            {CharacterName.Lucina,"ports any exact 0"},
            {CharacterName.Luigi,"modules solved n more 0"},
            {CharacterName.Mario,"time left less 101"},
            {CharacterName.Marth,"stage 3"},
            {CharacterName.MegaMan,"ports any exact 0"},
            {CharacterName.MetaKnight,"friend Kirby"},
            {CharacterName.Mewtwo,"ind compare lit"},
            {CharacterName.MinMin,"ind identify any FRK"},
            {CharacterName.MrGameWatch,"ports USB more 0"},
            {CharacterName.Ness,"ind identify lit NSA"},
            {CharacterName.Olimar,"batteries compare D"},
            {CharacterName.PacMan,"batteries AA exact 0"},
            {CharacterName.Palutena,"ind lit exact 0"},
            {CharacterName.Peach,"ind compare unlit"},
            {CharacterName.Pichu,"voltage kess 5.5"},
            {CharacterName.Pikachu,"kept"},
            {CharacterName.PiranhaPlant,"batteries all more 0"},
            {CharacterName.Pit,"ind identify unlit FRQ"},
            {CharacterName.PokémonTrainer,"ports StereoRCA exact 0"},
            {CharacterName.Pyra,"slot M"},
            {CharacterName.Richter,"slot M"},
            {CharacterName.Ridley,"ind identify lit MSA"},
            {CharacterName.ROB,"ports any exact 0"},
            {CharacterName.Robin,"time used more 50"},
            {CharacterName.Rosalina,"time used more 80"},
            {CharacterName.Roy,"ind any exact 0"},
            {CharacterName.Ryu,"sn last even"},
            {CharacterName.Samus,"time left less 361"},
            {CharacterName.Sephiroth,"ports any exact 0"},
            {CharacterName.Sheik,"kept"},
            {CharacterName.Shulk,"kept"},
            {CharacterName.Simon,"str 1left"},
            {CharacterName.Snake,"slot M"},
            {CharacterName.Sonic,"batteries all less 2"},
            {CharacterName.Sora, "ports onone StereoRCA|PS2"},
            {CharacterName.Steve,"needy"},
            {CharacterName.Terry,"ports ComponentVideo more 0"},
            {CharacterName.ToonLink,"ind identify unlit SND"},
            {CharacterName.Villager,"voltage less 2.5"},
            {CharacterName.Wario,"sn present M"},
            {CharacterName.WiiFitTrainer,"batteries compare D"},
            {CharacterName.Wolf,"widgetSum batteries|ports exact 5"},
            {CharacterName.Yoshi,"stage 1"},
            {CharacterName.YoungLink,"time left less 60"},
            {CharacterName.Zelda,"friend Link not"},
            {CharacterName.ZeroSuitSamus,"stage 1"}
        };
    }
}
